### ISSUE TITLE
Ajuster la taille du chat lors de l'affichage du modal détails

### ISSUE THREAD

**Issue by ellandri** [elsouleymane/assur-rh-front#9]
## Problème actuel
Le chat occupe actuellement trop d'espace lorsque le modal des détails s'affiche, ce qui rend l'interface moins ergonomique.

## Solution proposée
Modifier le CSS et le JavaScript pour:
1. Réduire la taille du chat quand le modal détails s'ouvre
2. Ajouter une transition fluide pour l'animation
3. Restaurer la taille originale quand le modal se ferme

### Modifications à apporter

1. Dans le CSS, ajouter des classes pour gérer l'état du chat:
```css
.chat-container.with-details {
    width: 60% !important;
    max-width: 700px !important;
    left: 50% !important;
    transform: translate(-100%, -50%) scale(1) !important;
}

.details-panel.active {
    width: 40%;
    max-width: 500px;
    right: auto;
    left: 50%;
    transform: translate(0%, -50%);
}
```

2. Dans le JavaScript, mettre à jour les fonctions:
```javascript
// Ajouter une constante pour les styles par défaut
const defaultChatStyles = {
    width: '90%',
    maxWidth: '800px',
    transform: 'translate(-50%, -50%) scale(1)',
    left: '50%'
};

// Mettre à jour openDestinationDetails
function openDestinationDetails(destinationKey) {
    // ... code existant ...
    chatContainer.classList.add('with-details');
}

// Mettre à jour closeDestinationDetails
function closeDestinationDetails() {
    detailsPanel.classList.remove('active');
    chatContainer.classList.remove('with-details');
}
```

## Impact attendu
- Meilleure utilisation de l'espace d'écran
- Interface plus intuitive
- Transition fluide entre les états

## Tests à effectuer
1. Vérifier que le redimensionnement est fluide
2. Tester sur différentes tailles d'écran
3. S'assurer que le contenu reste lisible
4. Vérifier que la restauration de taille fonctionne correctement
